######################################################
#   Triggers
######################################################
trigger:
  batch: true
  branches:
    include:
      - main
  
  paths:
    include:
    - Library/*
pr:
  branches:
    include:
      - main
  
  paths:
    include:
    - Library/*

######################################################
#   Resources
######################################################
resources:
  containers:
    - container: pg11
      image: ionx/postgres-plv8:11.1
      ports:
        - 5432:5432
    - container: pg10
      image: ionx/postgres-plv8:10.6
      ports:
        - 5432:5432
    - container: pg9.6
      image: mysticmind/postgres-plv8:9.6-1.4
      ports:
        - 5432:5432

######################################################
#   Variables
######################################################
variables:
  # .NET build variables
  dotnet_core_version: 3.1.x
  # Postgres variables
  pg_db: postgres_net_test
  testing_database: "Host=localhost;Port=5432;Database=postgres_net_test;Username=postgres;Password=Password12!"
  solution_path: Library/Postgres.NET.sln
  # NuGet variables
  major: 1
  minor: 0
  patch: $[counter(variables['minor'], 0)] #this will reset when we bump minor
  NugetVersion: $(major).$(minor).$(patch)
  AlphaNugetVersion: $(major).$(minor).$(patch)-alpha.1
  
  

######################################################
#   JOBS
######################################################
jobs:
  ####################################################
  #   JOB 1: Build Source Code
  ####################################################
  - template: jobs/job_1_build_with_multiple_os.yml

  ####################################################
  #   JOB 2: Test with different PG versions
  ####################################################
  - template: jobs/job_2_test_with_different_postgres_versions.yml
  
  ####################################################
  #   JOB 3: Publish Pre-release NuGet
  ####################################################
  - template: jobs/job_publish_nuget.yml
    parameters:
      name: Publish_Prerelease_NuGet
      dependsOn: Test
      nugetVersionEnv: 'AlphaNugetVersion'

  #####################################################
  #   JOB 4: Wait for NuGet to be published
  #####################################################
  - job: Wait
    dependsOn: Publish_Prerelease_NuGet
    pool: server    
    steps:
      - task: Delay@1
        inputs:
          delayForMinutes: '3' 
  
  #####################################################
  #   JOB 5: Perform contract tests to verify
  #          if there are no breaking change
  #####################################################
  - template: jobs/job_contract_tests_with_client_apps.yml

  #####################################################
  #   JOB 6: Publish NuGet
  #####################################################
  - template: jobs/job_publish_nuget.yml
    parameters:
      name: Publish_NuGet
      dependsOn: Contract_tests
      nugetVersionEnv: 'NugetVersion'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))